openapi: '3.0.0'
info:
  description: This specification is only for sample error response for API v2.
  version: '1.0'
  title: Sample Error Response
servers:
  - url: 'http://sample-service'
paths:
  /v2/sample/error:
    get:
      summary: Sample Request for Error Response
      responses:
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    InternalServerError:
      description: Server error. This should happen rarerly.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            timestamp: 2022-06-17T14:07:17Z
            trace_id: aswo3f-a202lfso-312123sld-1230dd1
            errors:
              - title: Internal error.
                details: Your request cannot be completed. Please try again later.
                type: https://developer.personio.de/reference/errors#sample.internal_error
  schemas:
    ErrorResponse:
      description: Invalid request response.
      type: object
      properties:
        timestamp:
          description: The timestamp.
          type: string
          format: date-time
          example: 2022-06-17T14:07:17Z
        trace_id:
          description: A unique trace ID.
          type: string
          format: uuid
          example: aswo3f-a202lfso-312123sld-1230dd1
        errors:
          description: List of errors
          type: array
          minItems: 1
          items:
            type: object
            properties:
              title:
                description: The title of the error.
                type: string
                example: Invalid credentials
              details:
                description: The description of the error.
                type: string
                example: The credentials were not correct. Make sure you are providing the right client_id and client_secret.
              type:
                description: Reference link to more details.
                type: string
                example: https://developer.personio.de/reference/errors#credentials.internal_error
            required:
              - title
              - details
              - type
      required:
        - timestamp
        - trace_id
        - errors
